spring:
  application:
    name: jwttest
  datasource:
    username: zyrhdb
    password: admin1357
    #username: root
    #password: root
    #    url: jdbc:mysql://localhost:3306/zyrhdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver #sql语句打印
    url: jdbc:p6spy:mysql://localhost:3306/zyrhdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8

jwt:
  tokenType: 'Bearer '  #JWT负载开头
  tokenHeader: Authorization #JWT存储的请求头
  secret: cuAihCz53DZRjZwbsGcZJ2Ai6At+T142uphtJMsk7iQ= #JWT加解密密钥
  expiration: 7200 #JWT的超期限时间(60*60*2)

secure:
  ignored:
    urls: #路径白名单
      - /user/testNoJwt
      - /user/login
      - /user/appLogin
      - /user/register
      - /basDevice/deviceCountInfo
      - /basDevice/deviceCountInfoByCompany
      - /basPoint/pointAndDevice
      - /basDevice/selectList
